### PR TITLE
Improvements : add classes

### PR DESCRIPTION
**Pull request by AmelieLaurens**
creation of a 'Polymer' and 'RJSMachine' classes
creation of polymer.yaml and machine.yaml
Modification of other scripts to use the value in polymer.yaml and machine.yaml

### CODE REVIEW

**Comment by AmelieLaurens** [comment]
issues : #12 and #13

**Review by ilyasst — CHANGES_REQUESTED** [review]
The `RJSMachine` and `Polymer` class  should have the content of their respective YAML files as attributes, but they do not. They only have a `self.doc` attribute that contains the content of the YAML file as a dictionary. 

I propose the following change here: create a new file called `deck.py` that will contain a class called `Deck( yaml_file_path )`. The Deck class will load the content of a single file called `deck.yaml` that will contain two sections: Machines and Polymers. The `RJSMachine` class will take a `deck = Deck( yaml_file_path )` object as an input and take from `deck.doc` the values stored in the Machines section of `deck.yaml` that will then become attributes of `RJSMachine`. Same thing for `Polymer`.

**Comment by AmelieLaurens** [comment]
Here are the changes requested.

**Review by ilyasst — APPROVED** [review]
Thank you for considering the proposed change.

**Pull request merged**
