### PR TITLE
Saving data in files .cvs

### PR DESCRIPTION
**Pull request by AmelieLaurens**
create a folder data_files which contains all the .cvs files with data

### CODE REVIEW

**Comment by AmelieLaurens** [comment]
Issue #26

**Comment by AmelieLaurens** [comment]
Issue #26

**Comment by AmelieLaurens** [comment]
Issue #26

**Comment by AmelieLaurens** [comment]
Issue #26

**Comment by AmelieLaurens** [comment]
Issue #26

**Comment by ilyasst** [comment]
@jaklengaigne Bump !

**Review by jaklengaigne — COMMENTED** [review]
@AmelieLaurens, I am wondering if that is the most practical way to save the data.
Would it be possible to pass by the same way as the graphics? Using the graphics class as it has the formating already. Or creating a separate class, along the same idea as the graphics class, where we pass the results of the computation and it save the results, instead of saving in the data class (which compute the results).

**Comment by jaklengaigne** [comment]
Close because correct and re-issued PR 32

**Pull request closed without merging**
